### ISSUE TITLE
Move module docs back into their respective modules, show separately

### ISSUE THREAD

**Issue by chillu** [silverstripe/userhelp.silverstripe.org#1]
At the moment we lump blog, userforms, forum, subsites into the same docs. That's confusing to users since they quite likely won't have these modules installed.
It also means we have nonsensical versioning information on them (forum doesn't have a 3.0, 3.1 version etc)

Move these guides back into the module codebase. Ideally we have a separate `docs/en/userhelp/index.md`, but this will necessitate some blacklist/whitelist feature in the docsviewer module so we don't also show this subfolder in the developer focused doc.silverstripe.org. @martimiz Maybe something you're keen to take on? :)

It'd be easier to do `docs_userhelp` as a separate toplevel folder. It clutters the folder structure, and is a bit too much duplication for my liking, but would do the trick.

**Comment by camfindlay** [comment]
I think as of 3.2 that userhelp docs won't be including module docs as they'll be part of the modules themselves. Once we switch versions we'll find out @tractorcow can you comment to this?

**Comment by camfindlay** [comment]
We are doing work now along these lines and moving more user guide documentation into modules then pulling this into userhelp.ss.org. Will update once complete I think it will solve this ticket.

**Comment by camfindlay** [comment]
This work was completed end of last year.
