### ISSUE TITLE
2.3.userhelp.silverstripe.org/ not found

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/userhelp.silverstripe.org#12]
The link on http://2.4.userhelp.silverstripe.org/ to 2.3 userhelp leads to the error message:

"...2.3.userhelp.silverstripe.org, which is pointing the SilverStripe server ernie.knossos.silverstripe.com, but is no longer hosted here."

**Comment by camfindlay** [comment]
corrected.
